"""core rev 032 — branches.id identity BY DEFAULT (ticket #34, S5.4)

The chain consumer replays `entity='branch'` fan-out copies with the
OUTBOX payload's explicit id so every peer converges on one shared branch id
(#33 precedent: versioned replay needs BY DEFAULT identities). rev 001
created branches.id as GENERATED ALWAYS, which rejects explicit-id inserts
(OVERRIDING SYSTEM VALUE would be needed per-statement); flipping the column
to BY DEFAULT keeps the sequence and lets the ORM insert replayed rows
verbatim. SQLite twin is unaffected — INTEGER PRIMARY KEY AUTOINCREMENT
already accepts explicit ids; the twin script records the revision only.
"""
from alembic import op

revision = "032_branch_identity_by_default"
down_revision = "031_needs_orders"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE branches ALTER COLUMN id SET GENERATED BY DEFAULT")


def downgrade() -> None:
    op.execute(
        "SELECT setval(pg_get_serial_sequence('branches', 'id'), "
        "(SELECT COALESCE(MAX(id), 1) FROM branches))"
    )
    op.execute("ALTER TABLE branches ALTER COLUMN id SET GENERATED ALWAYS")
