"""SQLAlchemy models for the tables this ticket's plumbing touches.

Columns mirror `alembic/versions/001_core_schema.py` EXACTLY — no invented
columns, no schema changes (ticket #2 constraint). These are hand-written
models for the seams being built here (auth, audit/outbox, stock-movement
demo); they are NOT autogenerated from or used to alter the schema.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Identity,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import ENUM, JSONB, TIMESTAMP
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


# --- enums shared by model columns (already created by rev 001) ---
tax_type_enum = ENUM("exempt", "5%", "14%", name="tax_type", create_type=False)
batch_type_enum = ENUM(
    "purchase", "sale", "return", "count", "transfer_in", "transfer_out",
    "opening", "correction", name="batch_type", create_type=False,
)
sync_status_enum = ENUM(
    "pending", "applied", "failed", "skipped", name="sync_status", create_type=False,
)
invoice_kind_enum = ENUM(
    "sale", "purchase", "sale_return", "purchase_return", "transfer",
    name="invoice_kind", create_type=False,
)
invoice_status_enum = ENUM(
    "saved", "unsaved", "unsave", "copy", "transfer_to_sale_return",
    "transfer_to_purchase", "closed", "archived", "void", name="invoice_status",
    create_type=False,
)

user_roles_table = Table(
    "user_roles",
    Base.metadata,
    Column("user_id", BigInteger, ForeignKey("users.id"), primary_key=True),
    Column("role_id", BigInteger, ForeignKey("roles.id"), primary_key=True),
)

role_permissions_table = Table(
    "role_permissions",
    Base.metadata,
    Column("role_id", BigInteger, ForeignKey("roles.id"), primary_key=True),
    Column("permission_id", BigInteger, ForeignKey("permissions.id"), primary_key=True),
)


class Branch(Base):
    """`branches` (wzphar) — mirrored from rev 001 so FKs resolve; used by
    branch-scoped write paths. Not a full domain object yet."""

    __tablename__ = "branches"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    pharmacyid: Mapped[str] = mapped_column(String(15), nullable=False)
    phar: Mapped[str] = mapped_column(String(15), server_default="")
    mobile: Mapped[str] = mapped_column(String(15), nullable=False)
    pharname: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    adress: Mapped[Optional[str]] = mapped_column(String(200), server_default="")
    governorate: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    district: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    country: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    currency: Mapped[Optional[str]] = mapped_column(String(10), server_default="")
    vat_default: Mapped[object] = mapped_column(
        Numeric(5, 2), nullable=False, server_default=text("14.00")
    )
    vat_inclusive_prices: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    is_main_device: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class Role(Base):
    __tablename__ = "roles"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    name: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    description: Mapped[str] = mapped_column(String(200), server_default="")

    users: Mapped[list["User"]] = relationship(secondary=user_roles_table, back_populates="roles")


class Permission(Base):
    __tablename__ = "permissions"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    code: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    name_ar: Mapped[str] = mapped_column(String(100), server_default="")


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    username: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    namee: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    mobile: Mapped[Optional[str]] = mapped_column(String(15), server_default="")
    pass_hash: Mapped[str] = mapped_column(String(255), server_default="")
    permission_level: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default="1")
    branch_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("branches.id"))
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )

    roles: Mapped[list[Role]] = relationship(secondary=user_roles_table, back_populates="users")


class Drug(Base):
    __tablename__ = "drugs"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    drugname: Mapped[str] = mapped_column(String(100), nullable=False)
    drugnamear: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    generic: Mapped[Optional[str]] = mapped_column(String(120), server_default="")
    classy: Mapped[Optional[str]] = mapped_column(String(35), server_default="")
    pharmacology: Mapped[Optional[str]] = mapped_column(String(200), server_default="")
    co: Mapped[Optional[str]] = mapped_column(String(100), server_default="")
    unitsclass: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    tax_type: Mapped[str] = mapped_column(tax_type_enum, nullable=False, server_default="exempt")
    vat: Mapped[Optional[object]] = mapped_column(Numeric(5, 2), nullable=False, server_default="0")
    units: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    unitsmall: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    price: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    price_wholesale: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    price_cost: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    price_now: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    disco: Mapped[Optional[object]] = mapped_column(Numeric(5, 2), server_default="0")
    pricechanged: Mapped[Optional[bool]] = mapped_column(Boolean, server_default="false")
    localimport: Mapped[Optional[int]] = mapped_column(Integer, server_default="0")
    titanid: Mapped[Optional[int]] = mapped_column(Integer, server_default="0")
    history: Mapped[Optional[str]] = mapped_column(Text(), server_default="")
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    lastedit: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))

    barcodes: Mapped[list["DrugBarcode"]] = relationship(
        back_populates="drug", cascade="all, delete-orphan"
    )


class DrugBarcode(Base):
    """`drug_barcodes` — a drug's up-to-6 codes (wzdrugs barcode + Barcode1..5).

    Partial-unique `barcode` (WHERE barcode <> '') prevents two drugs sharing a
    code without blocking the empty-string default rows (plan/01 §1.3#4).
    """

    __tablename__ = "drug_barcodes"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    drug_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("drugs.id"), nullable=False)
    barcode: Mapped[str] = mapped_column(String(16), nullable=False)
    is_primary: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")

    drug: Mapped[Drug] = relationship(back_populates="barcodes")


class PriceChangeLog(Base):
    """`price_change_log` (storediscount lineage, plan/02 §4.6) — one row per
    price change on a drug, written in the same transaction as the drug write."""

    __tablename__ = "price_change_log"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("branches.id"))
    drug_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("drugs.id"))
    barcode: Mapped[str] = mapped_column(String(16), server_default="")
    price: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    disco: Mapped[Optional[object]] = mapped_column(Numeric(5, 2), server_default="0")
    units: Mapped[int] = mapped_column(Integer, server_default="0")
    quant: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    datee: Mapped[Optional[date]] = mapped_column(Date)
    tips: Mapped[str] = mapped_column(String(200), server_default="")
    country: Mapped[str] = mapped_column(String(50), server_default="")
    storename: Mapped[str] = mapped_column(String(100), server_default="")
    pharmacyname: Mapped[str] = mapped_column(String(100), server_default="")
    pharmacyname2: Mapped[str] = mapped_column(String(100), server_default="")
    titanver: Mapped[str] = mapped_column(String(20), server_default="")
    pricechanged: Mapped[Optional[bool]] = mapped_column(Boolean, server_default="false")
    localimport: Mapped[Optional[int]] = mapped_column(Integer, server_default="0")
    changed_by: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("users.id"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class StockBatch(Base):
    __tablename__ = "stock_batches"
    __table_args__ = (
        UniqueConstraint("branch_id", "drug_id", "randomid", name="uq_stock_batches"),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    drug_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("drugs.id"), nullable=False)
    randomid: Mapped[str] = mapped_column(String(50), nullable=False)
    qty: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    expire: Mapped[Optional[date]] = mapped_column(Date)
    cost: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    vat: Mapped[object] = mapped_column(Numeric(5, 2), nullable=False, server_default="0")
    price: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    oldstock: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    typee: Mapped[str] = mapped_column(batch_type_enum, nullable=False, server_default="purchase")
    vatvalue: Mapped[Optional[object]] = mapped_column(Numeric(18, 2), server_default="0")
    totalwithvat: Mapped[Optional[object]] = mapped_column(Numeric(18, 2), server_default="0")
    writer: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    classy: Mapped[Optional[str]] = mapped_column(String(35), server_default="")
    created_by: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("users.id"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class BranchStock(Base):
    __tablename__ = "branch_stock"

    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), primary_key=True)
    drug_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("drugs.id"), primary_key=True)
    qty: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    minimum: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    silsilaid: Mapped[Optional[str]] = mapped_column(String(15), server_default="")
    classy: Mapped[Optional[str]] = mapped_column(String(35), server_default="")
    price: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    barcode: Mapped[Optional[str]] = mapped_column(String(16), server_default="")
    lastedit: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("branches.id"))
    user_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("users.id"))
    entity: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    field: Mapped[str] = mapped_column(String(50), server_default="")
    old_value: Mapped[Optional[str]] = mapped_column(Text())
    new_value: Mapped[Optional[str]] = mapped_column(Text())
    drug_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("drugs.id"))
    barcode: Mapped[str] = mapped_column(String(16), server_default="")
    action: Mapped[str] = mapped_column(String(30), nullable=False, server_default="update")
    namee: Mapped[str] = mapped_column(String(100), server_default="")
    typevalue: Mapped[str] = mapped_column(String(100), server_default="")
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class SyncLog(Base):
    __tablename__ = "sync_log"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    entity: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    action: Mapped[str] = mapped_column(String(30), nullable=False, server_default="update")
    payload: Mapped[Optional[dict]] = mapped_column(JSONB)
    synced_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    status: Mapped[str] = mapped_column(sync_status_enum, nullable=False, server_default="pending")
    source_device_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("branches.id"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class Party(Base):
    """`parties` (wzcustomers + companies) — mirrored so Invoice FKs resolve."""

    __tablename__ = "parties"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    kind: Mapped[str] = mapped_column(
        ENUM("customer", "supplier", "both", name="party_kind", create_type=False),
        nullable=False,
        server_default="customer",
    )
    typee: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    namee: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    name_ar: Mapped[Optional[str]] = mapped_column(String(100), server_default="")
    mobile: Mapped[Optional[str]] = mapped_column(String(15), server_default="")
    adress: Mapped[Optional[str]] = mapped_column(String(200), server_default="")
    governorate: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    district: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    credit_limit: Mapped[object] = mapped_column(Numeric(18, 2), nullable=False, server_default="0")
    receivable_account_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("accounts.id"))
    payable_account_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("accounts.id"))
    writer: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    randomid: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    datee: Mapped[Optional[date]] = mapped_column(Date)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class Invoice(Base):
    """`invoices` header (C-4). Columns mirror rev 001 EXACTLY — the sale slice
    (S1.3) owns the money/journal/stock logic; `save_sale` is the bus seam."""

    __tablename__ = "invoices"
    __table_args__ = (
        UniqueConstraint("branch_id", "invoice_no", name="uq_invoices_branch_no"),
        CheckConstraint("payed + agel = totalvalue", name="ck_invoice_payment"),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    kind: Mapped[str] = mapped_column(invoice_kind_enum, nullable=False, server_default="sale")
    invoice_no: Mapped[str] = mapped_column(String(30), nullable=False)
    datee: Mapped[date] = mapped_column(Date, nullable=False)
    datetimee: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    silsilaid: Mapped[Optional[str]] = mapped_column(String(15), server_default="")
    party_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("parties.id"))
    subtotal: Mapped[object] = mapped_column(Numeric(18, 2), nullable=False, server_default="0")
    discount: Mapped[object] = mapped_column(Numeric(18, 2), nullable=False, server_default="0")
    vat: Mapped[object] = mapped_column(Numeric(18, 2), nullable=False, server_default="0")
    totalvalue: Mapped[object] = mapped_column(Numeric(18, 2), nullable=False, server_default="0")
    payed: Mapped[object] = mapped_column(Numeric(18, 2), nullable=False, server_default="0")
    agel: Mapped[object] = mapped_column(Numeric(18, 2), nullable=False, server_default="0")
    status: Mapped[str] = mapped_column(invoice_status_enum, nullable=False, server_default="saved")
    writer: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    created_by: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("users.id"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    last_edited_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))


class AppPlugin(Base):
    """`app_plugins` — installed plugin registry rows (core rev 001, C-13)."""

    __tablename__ = "app_plugins"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    slug: Mapped[str] = mapped_column(String(60), nullable=False, unique=True)
    name_ar: Mapped[str] = mapped_column(String(120), nullable=False)
    name_en: Mapped[str] = mapped_column(String(120), nullable=False)
    version: Mapped[str] = mapped_column(String(20), nullable=False)
    core_requires: Mapped[str] = mapped_column(String(60), nullable=False)
    sdk_version: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="installed")
    license_status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="unlicensed")
    license_expires_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    installed_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class PluginDependencyRow(Base):
    """`plugin_dependencies` — one row per declared dependency (C-13)."""

    __tablename__ = "plugin_dependencies"

    plugin_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("app_plugins.id"), primary_key=True
    )
    depends_on: Mapped[str] = mapped_column(String(60), primary_key=True)
    min_version: Mapped[str] = mapped_column(String(20), nullable=False)
    max_version: Mapped[Optional[str]] = mapped_column(String(20))


class PluginBranchGrant(Base):
    """`plugin_branch_grants` — per-branch enablement (C-13, plan/08 §4.3)."""

    __tablename__ = "plugin_branch_grants"

    plugin_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("app_plugins.id"), primary_key=True
    )
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), primary_key=True)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))


class PluginSettings(Base):
    """`plugin_settings` — per (branch, plugin, key) JSON settings (C-13)."""

    __tablename__ = "plugin_settings"

    branch_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("branches.id"), primary_key=True
    )
    plugin_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("app_plugins.id"), primary_key=True)
    key: Mapped[str] = mapped_column(String(80), primary_key=True)
    value: Mapped[Optional[dict]] = mapped_column(JSONB)
    encrypted: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class AppConfig(Base):
    """`app_config` — key/value application config (incl. `plugins_enabled`)."""

    __tablename__ = "app_config"

    key: Mapped[str] = mapped_column(String(50), primary_key=True)
    value: Mapped[str] = mapped_column(String(50), server_default="")
    value_numeric: Mapped[Optional[object]] = mapped_column(Numeric(18, 4))
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )