"""SQLAlchemy models for the tables this ticket's plumbing touches.

Columns mirror `alembic/versions/001_core_schema.py` EXACTLY — no invented
columns, no schema changes (ticket #2 constraint). These are hand-written
models for the seams being built here (auth, audit/outbox, stock-movement
demo); they are NOT autogenerated from or used to alter the schema.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Identity,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import ENUM, JSONB, TIMESTAMP
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


# --- enums shared by model columns (already created by rev 001) ---
tax_type_enum = ENUM("exempt", "5%", "14%", name="tax_type", create_type=False)
batch_type_enum = ENUM(
    "purchase", "sale", "return", "count", "transfer_in", "transfer_out",
    "opening", "correction", name="batch_type", create_type=False,
)
sync_status_enum = ENUM(
    "pending", "applied", "failed", "skipped", name="sync_status", create_type=False,
)

user_roles_table = Table(
    "user_roles",
    Base.metadata,
    Column("user_id", BigInteger, ForeignKey("users.id"), primary_key=True),
    Column("role_id", BigInteger, ForeignKey("roles.id"), primary_key=True),
)


class Branch(Base):
    """`branches` (wzphar) — mirrored from rev 001 so FKs resolve; used by
    branch-scoped write paths. Not a full domain object yet."""

    __tablename__ = "branches"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    pharmacyid: Mapped[str] = mapped_column(String(15), nullable=False)
    phar: Mapped[str] = mapped_column(String(15), server_default="")
    mobile: Mapped[str] = mapped_column(String(15), nullable=False)
    pharname: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    adress: Mapped[Optional[str]] = mapped_column(String(200), server_default="")
    governorate: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    district: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    country: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    currency: Mapped[Optional[str]] = mapped_column(String(10), server_default="")
    vat_default: Mapped[object] = mapped_column(
        Numeric(5, 2), nullable=False, server_default=text("14.00")
    )
    vat_inclusive_prices: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    is_main_device: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class Role(Base):
    __tablename__ = "roles"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    name: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    description: Mapped[str] = mapped_column(String(200), server_default="")

    users: Mapped[list["User"]] = relationship(secondary=user_roles_table, back_populates="roles")


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    username: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    namee: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    mobile: Mapped[Optional[str]] = mapped_column(String(15), server_default="")
    pass_hash: Mapped[str] = mapped_column(String(255), server_default="")
    permission_level: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default="1")
    branch_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("branches.id"))
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )

    roles: Mapped[list[Role]] = relationship(secondary=user_roles_table, back_populates="users")


class Drug(Base):
    __tablename__ = "drugs"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    drugname: Mapped[str] = mapped_column(String(100), nullable=False)
    drugnamear: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    generic: Mapped[Optional[str]] = mapped_column(String(120), server_default="")
    classy: Mapped[Optional[str]] = mapped_column(String(35), server_default="")
    pharmacology: Mapped[Optional[str]] = mapped_column(String(200), server_default="")
    co: Mapped[Optional[str]] = mapped_column(String(100), server_default="")
    unitsclass: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    tax_type: Mapped[str] = mapped_column(tax_type_enum, nullable=False, server_default="exempt")
    vat: Mapped[Optional[object]] = mapped_column(Numeric(5, 2), nullable=False, server_default="0")
    units: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    unitsmall: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    price: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    price_now: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    disco: Mapped[Optional[object]] = mapped_column(Numeric(5, 2), server_default="0")
    pricechanged: Mapped[Optional[bool]] = mapped_column(Boolean, server_default="false")
    localimport: Mapped[Optional[int]] = mapped_column(Integer, server_default="0")
    titanid: Mapped[Optional[int]] = mapped_column(Integer, server_default="0")
    history: Mapped[Optional[str]] = mapped_column(Text(), server_default="")
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    lastedit: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))


class StockBatch(Base):
    __tablename__ = "stock_batches"
    __table_args__ = (
        UniqueConstraint("branch_id", "drug_id", "randomid", name="uq_stock_batches"),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    drug_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("drugs.id"), nullable=False)
    randomid: Mapped[str] = mapped_column(String(50), nullable=False)
    qty: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    expire: Mapped[Optional[date]] = mapped_column(Date)
    cost: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    vat: Mapped[object] = mapped_column(Numeric(5, 2), nullable=False, server_default="0")
    price: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    oldstock: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    typee: Mapped[str] = mapped_column(batch_type_enum, nullable=False, server_default="purchase")
    vatvalue: Mapped[Optional[object]] = mapped_column(Numeric(18, 2), server_default="0")
    totalwithvat: Mapped[Optional[object]] = mapped_column(Numeric(18, 2), server_default="0")
    writer: Mapped[Optional[str]] = mapped_column(String(50), server_default="")
    classy: Mapped[Optional[str]] = mapped_column(String(35), server_default="")
    created_by: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("users.id"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class BranchStock(Base):
    __tablename__ = "branch_stock"

    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), primary_key=True)
    drug_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("drugs.id"), primary_key=True)
    qty: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    minimum: Mapped[object] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    silsilaid: Mapped[Optional[str]] = mapped_column(String(15), server_default="")
    classy: Mapped[Optional[str]] = mapped_column(String(35), server_default="")
    price: Mapped[Optional[object]] = mapped_column(Numeric(18, 4), server_default="0")
    barcode: Mapped[Optional[str]] = mapped_column(String(16), server_default="")
    lastedit: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("branches.id"))
    user_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("users.id"))
    entity: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    field: Mapped[str] = mapped_column(String(50), server_default="")
    old_value: Mapped[Optional[str]] = mapped_column(Text())
    new_value: Mapped[Optional[str]] = mapped_column(Text())
    drug_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("drugs.id"))
    barcode: Mapped[str] = mapped_column(String(16), server_default="")
    action: Mapped[str] = mapped_column(String(30), nullable=False, server_default="update")
    namee: Mapped[str] = mapped_column(String(100), server_default="")
    typevalue: Mapped[str] = mapped_column(String(100), server_default="")
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class SyncLog(Base):
    __tablename__ = "sync_log"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    entity: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    action: Mapped[str] = mapped_column(String(30), nullable=False, server_default="update")
    payload: Mapped[Optional[dict]] = mapped_column(JSONB)
    synced_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    status: Mapped[str] = mapped_column(sync_status_enum, nullable=False, server_default="pending")
    source_device_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("branches.id"))
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )