"""SQLAlchemy models package.

Columns mirror `alembic/versions/001_core_schema.py` EXACTLY — no invented
columns, no schema changes (ticket #2 constraint). These are hand-written
models for the seams being built (auth, audit/outbox, drug master, sales,
plugins); they are NOT autogenerated from or used to alter the schema.

Split into small focused modules (one domain per file) — keep it that way:
add new tables to the module that owns their domain, then re-export here so
`from app.models import X` keeps working across the codebase.
"""
from app.models.accounting import Account, Balance, Journal, JournalLine, Party
from app.models.auth import Permission, Role, User
from app.models.base import (
    Base,
    account_type_enum,
    batch_type_enum,
    close_status_enum,
    correction_status_enum,
    drawer_direction_enum,
    drawer_method_enum,
    drawer_reason_enum,
    invoice_kind_enum,
    invoice_status_enum,
    journal_source_enum,
    payment_method_enum,
    role_permissions_table,
    sync_status_enum,
    tax_type_enum,
    user_roles_table,
)
from app.models.core import AppConfig, AuditLog, Branch, SyncLog
from app.models.drawer import DailyClose, DrawerMovement
from app.models.drugs import Drug, DrugBarcode, PriceChangeLog
from app.models.plugins import AppPlugin, PluginBranchGrant, PluginDependencyRow, PluginSettings
from app.models.sales import Invoice, InvoiceLine, InvoiceVersion, PaymentSplit
from app.models.stock import BranchStock, StockBatch, StockCorrectionRequest

__all__ = [
    "Account",
    "AppConfig",
    "AppPlugin",
    "AuditLog",
    "Balance",
    "Base",
    "Branch",
    "BranchStock",
    "DailyClose",
    "DrawerMovement",
    "Drug",
    "DrugBarcode",
    "Invoice",
    "InvoiceLine",
    "InvoiceVersion",
    "Journal",
    "JournalLine",
    "Party",
    "PaymentSplit",
    "Permission",
    "PluginBranchGrant",
    "PluginDependencyRow",
    "PluginSettings",
    "PriceChangeLog",
    "Role",
    "StockBatch",
    "StockCorrectionRequest",
    "SyncLog",
    "User",
    "account_type_enum",
    "batch_type_enum",
    "close_status_enum",
    "correction_status_enum",
    "drawer_direction_enum",
    "drawer_method_enum",
    "drawer_reason_enum",
    "invoice_kind_enum",
    "invoice_status_enum",
    "journal_source_enum",
    "payment_method_enum",
    "role_permissions_table",
    "sync_status_enum",
    "tax_type_enum",
    "user_roles_table",
]