"""Chain-buy + dead-stock exchange models (ticket #36, S5.6; rev 035).

`chain_buy_orders` — merged 12-col ChainBuyStore/ChainBuyUsers (ChainBuyStore
StoreName, PharmacistTel, RequisterTel, Quant, price, SellDisc, Expire, Tips,
Mohafaza/Markaz, country, IdDateTime, transfer_status). Columns mirror
`alembic/versions/035_chain_buy.py` verbatim plus CHECKs/FKs and updated_at.

`dead_stock_exchange` — RawakidTablew (رواكد) 12-col SourceIdDateTime variant.
Both tables shipped in CORE rev 035 (ADR-0002 T1 precedent — logistics plugin
deferred, G12 atomicity is core). Identity is GENERATED BY DEFAULT so offline
replay can insert explicit ids.
"""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import CheckConstraint, Date, ForeignKey, Identity, Numeric, String, text
from sqlalchemy import BigInteger
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class ChainBuyOrder(Base):
    """`chain_buy_orders` — chain buy request (←ChainBuyStore + ChainBuyUsers)."""

    __tablename__ = "chain_buy_orders"
    __table_args__ = (
        CheckConstraint("qty > 0", name="ck_chain_buy_qty_positive"),
        CheckConstraint("price >= 0", name="ck_chain_buy_price_nonneg"),
        CheckConstraint(
            "status IN ('created', 'in_transit', 'delivered', 'received', 'cancelled')",
            name="ck_chain_buy_status",
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=False), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    drug_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("drugs.id"), nullable=False)
    store_name: Mapped[str] = mapped_column(String(100), nullable=False, server_default="")
    pharmacist_tel: Mapped[str] = mapped_column(String(15), nullable=False, server_default="")
    requester_tel: Mapped[str] = mapped_column(String(15), nullable=False, server_default="")
    qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    sell_disc: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False, server_default="0")
    expire: Mapped[Optional[date]] = mapped_column(Date)
    tips: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    governorate: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    district: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    country: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    iddatetime: Mapped[Optional[datetime]] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("now()")
    )
    status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="created")
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))


class DeadStockExchange(Base):
    """`dead_stock_exchange` — dead-stock / رواكد offer (←RawakidTablew)."""

    __tablename__ = "dead_stock_exchange"
    __table_args__ = (
        CheckConstraint("qty > 0", name="ck_dead_stock_qty_positive"),
        CheckConstraint("price >= 0", name="ck_dead_stock_price_nonneg"),
        CheckConstraint(
            "status IN ('created', 'in_transit', 'delivered', 'received', 'cancelled')",
            name="ck_dead_stock_status",
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=False), primary_key=True)
    branch_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("branches.id"), nullable=False)
    drug_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("drugs.id"), nullable=False)
    qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    expire: Mapped[Optional[date]] = mapped_column(Date)
    price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False, server_default="0")
    sell_disc: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False, server_default="0")
    tips: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    governorate: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    district: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    source_pharmacist_tel: Mapped[str] = mapped_column(String(15), nullable=False, server_default="")
    requester_tel: Mapped[str] = mapped_column(String(15), nullable=False, server_default="")
    source_iddatetime: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    country: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="created")
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
