' ==============================================
' Class: ModNilsen
' Procedures: 20
' ==============================================

' --- Proc @ 0x0092c574 (size=124, frame=20) ---
Private Sub Proc_0x0092c574()
On Error GoTo ErrHandler
_CallImp_
If Not _condition_ Then
    Exit Sub
    _CallImp_
    _CallImp_
    Exit Sub
End Sub

' --- Proc @ 0x008dfbb8 (size=12, frame=16) ---
Private Sub Proc_0x008dfbb8()
_CallImp_
Exit Sub
End Sub

' --- Proc @ 0x00977420 (size=252, frame=184) ---
Private Sub Proc_0x00977420()
On Error GoTo ErrHandler
36 = "r"
_CallImp_
_VariantValue_ = _VarRef_
If Not _condition_ Then
    Exit Sub
    _VarRef_ = " "
    _CallImp_
    _CallImp_
    " " = "'"
    _CallImp_
    0 = "D"
    _CallImp_
    Exit Sub
    _CallImp_
    _Property_ = _VarRef_
    _CallImp_
    Exit Sub
End Sub

' --- Proc @ 0x00900ea8 (size=64, frame=36) ---
Private Sub Proc_0x00900ea8()
_CallImp_
_CallImp_
Exit Sub
End Sub

' --- Proc @ 0x009a491c (size=320, frame=208) ---
Private Sub Proc_0x009a491c()
_CallImp_
_CallImp_
1 = "Y"
_CallImp_
_CallImp_
3 = ((1 & ((_MemProperty_ & (_MemProperty_ & ".")) & ".")) & ".")
_VarRef_ = ((100000 & "/") & "/")
_VarRef_ = _VarRef_
_CallImp_
_CallImp_
_VarRef_ = _VarRef_
_CallImp_
If Not _condition_ Then
    _CallImp_
    _CallImp_
    _CallImp_
    _CallImp_
    Exit Sub
End Sub

' --- Proc @ 0x00abbe20 (size=1632, frame=424) ---
Private Sub Proc_0x00abbe20()
On Error GoTo ErrHandler
_CallImp_
_CallImp_
_CallImp_
If Not _condition_ Then
    _MemProperty_ = _MemProperty_
    If Not _condition_ Then
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _MemProperty_ = ";"
        1 = "Y"
        _CallImp_
        _VarRef_ = ";"
        1 = "H"
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _MemProperty_ = ";"
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _VarRef_ = ";"
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        100 = ";"
        _CallImp_
        _CallImp_
        _CallImp_
        _Variable_ = ";"
        _CallImp_
        _CallImp_
        _CallImp_
        _CallImp_
        1 = "Y"
        _CallImp_
        _CallImp_
        3 = ((((1 & ((_MemProperty_ & (_MemProperty_ & ".")) & ".")) & ".") & "/") & "/")
        100000 = _VarRef_
        _CallImp_
        _CallImp_
        _CallImp_
        _CallImp_
        _CallImp_
        Exit Sub
End Sub

' --- Proc @ 0x00aba8a0 (size=1624, frame=424) ---
Private Sub Proc_0x00aba8a0()
On Error GoTo ErrHandler
_CallImp_
_CallImp_
_CallImp_
If Not _condition_ Then
    _MemProperty_ = _MemProperty_
    If Not _condition_ Then
        _CallImp_
        If Not _condition_ Then
            _CallImp_
            _VarRef_ = ";"
            _CallImp_
            _CallImp_
            _MemProperty_ = ";"
            _CallImp_
            _CallImp_
            _CallImp_
            _CallImp_
            _MemProperty_ = ";"
            _MemProperty_ = ";"
            1 = "Y"
            _CallImp_
            _VarRef_ = ";"
            1 = "H"
            _CallImp_
            _VarRef_ = ";"
            _CallImp_
            _VarRef_ = ";"
            _CallImp_
            _MemProperty_ = ";"
            _MemProperty_ = ";"
            _CallImp_
            _CallImp_
            _MemProperty_ = ";"
            _CallImp_
            _VarRef_ = ";"
            _MemProperty_ = ";"
            _CallImp_
            _CallImp_
            _MemProperty_ = ";"
            _CallImp_
            _CallImp_
            100 = ";"
            _CallImp_
            _CallImp_
            _CallImp_
            _Variable_ = ";"
            _CallImp_
            _CallImp_
            _CallImp_
            _CallImp_
            1 = "Y"
            _CallImp_
            _CallImp_
            3 = ((((1 & ((_MemProperty_ & (_MemProperty_ & ".")) & ".")) & ".") & "/") & "/")
            100000 = _VarRef_
            _CallImp_
            _CallImp_
            _CallImp_
            _CallImp_
            _CallImp_
            Exit Sub
End Sub

' --- Proc @ 0x00b392b0 (size=6144, frame=4) ---
Private Sub Proc_0x00b392b0()
On Error GoTo ErrHandler
If Not _condition_ Then
    If Not _condition_ Then
        If Not _condition_ Then
            If Not _condition_ Then
                If Not _condition_ Then
                    If Not _condition_ Then
                        If Not _condition_ Then
                            If Not _condition_ Then
                                If Not _condition_ Then
                                    If Not _condition_ Then
                                        If Not _condition_ Then
                                            If Not _condition_ Then
                                                If Not _condition_ Then
                                                    If Not _condition_ Then
                                                        If Not _condition_ Then
                                                            If Not _condition_ Then
                                                                If Not _condition_ Then
                                                                    If Not _condition_ Then
                                                                        If Not _condition_ Then
                                                                            If Not _condition_ Then
                                                                                If Not _condition_ Then
                                                                                    If Not _condition_ Then
                                                                                        If Not _condition_ Then
                                                                                            If Not _condition_ Then
                                                                                                If Not _condition_ Then
                                                                                                    If Not _condition_ Then
                                                                                                        If Not _condition_ Then
                                                                                                            If Not _condition_ Then
                                                                                                                If Not _condition_ Then
                                                                                                                    If Not _condition_ Then
                                                                                                                        If Not _condition_ Then
                                                                                                                            If Not _condition_ Then
                                                                                                                                If Not _condition_ Then
                                                                                                                                    If Not _condition_ Then
                                                                                                                                        If Not _condition_ Then
                                                                                                                                            If Not _condition_ Then
                                                                                                                                                If Not _condition_ Then
                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    If Not _condition_ Then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        If Not _condition_ Then
End Sub

' --- Proc @ 0x009a2d04 (size=364, frame=92) ---
Private Sub Proc_0x009a2d04()
_CallImp_
If Not _condition_ Then
    _CallImp_
    If Not _condition_ Then
        _VariantValue_ = _VariantValue_
        _CallImp_
        If Not _condition_ Then
            _VariantValue_ = _VariantValue_
            _CallImp_
            _CallImp_
            _CallImp_
            _CallImp_
            If Not _condition_ Then
                _CallImp_
                If Not _condition_ Then
                    _VariantValue_ = _VariantValue_
                    _CallImp_
                    If Not _condition_ Then
                        _VariantValue_ = _VariantValue_
                        _CallImp_
                        _CallImp_
                        _CallImp_
End Sub

' --- Proc @ 0x009a2b5c (size=364, frame=92) ---
Private Sub Proc_0x009a2b5c()
_CallImp_
If Not _condition_ Then
    _CallImp_
    If Not _condition_ Then
        _VariantValue_ = _VariantValue_
        _CallImp_
        If Not _condition_ Then
            _VariantValue_ = _VariantValue_
            _CallImp_
            _CallImp_
            _CallImp_
            _CallImp_
            If Not _condition_ Then
                _CallImp_
                If Not _condition_ Then
                    _VariantValue_ = _VariantValue_
                    _CallImp_
                    If Not _condition_ Then
                        _VariantValue_ = _VariantValue_
                        _CallImp_
                        _CallImp_
                        _CallImp_
End Sub

' --- Proc @ 0x008f2ee0 (size=44, frame=32) ---
Private Sub Proc_0x008f2ee0()
_CallImp_
If Not _condition_ Then
End If
End Sub

' --- Proc @ 0x00979374 (size=276, frame=12) ---
Private Sub Proc_0x00979374()
_CallImp_
_CallImp_
_CallImp_
_CallImp_
_CallImp_
_CallImp_
_CallImp_
_CallImp_
Exit Sub
End Sub

' --- Proc @ 0x009c8b1c (size=376, frame=328) ---
Private Sub Proc_0x009c8b1c()
_CallImp_
_CallImp_
If Not _condition_ Then
    If Not _condition_ Then
        If Not _condition_ Then
            If Not _condition_ Then
                _VarRef_ = _VarRef_
                If Not _condition_ Then
End Sub

' --- Proc @ 0x00aaf4e0 (size=1528, frame=408) ---
Private Sub Proc_0x00aaf4e0()
On Error GoTo ErrHandler
_CallImp_
_CallImp_
_CallImp_
On Error GoTo ErrHandler
_CallImp_
_CallImp_
If Not _condition_ Then
    _MemProperty_ = _MemProperty_
    If Not _condition_ Then
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _MemProperty_ = ";"
        1 = "Y"
        _CallImp_
        _VarRef_ = ";"
        1 = "H"
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _MemProperty_ = ";"
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _VarRef_ = ";"
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        100 = ";"
        _CallImp_
        _CallImp_
        _CallImp_
        _Variable_ = ";"
        1 = "Y"
        _CallImp_
        _CallImp_
        _MemProperty_ = ((_MemProperty_ & "6") & ".")
        _CallImp_
        0 = "D"
        _CallImp_
        Exit Sub
End Sub

' --- Proc @ 0x008ef0a4 (size=36, frame=4) ---
Private Sub Proc_0x008ef0a4()
_CallImp_
If Not _condition_ Then
    _CallImp_
    If Not _condition_ Then
        Exit Sub
End Sub

' --- Proc @ 0x00a7fd34 (size=1076, frame=484) ---
Private Sub Proc_0x00a7fd34()
_CallImp_
_var_ = _VariantValue_
_CallImp_
_var_ = _VarRef_
_CallImp_
_var_ = _VarRef_
_CallImp_
_var_ = _value_
If Not _condition_ Then
    _MemProperty_ = _MemProperty_
    _CallImp_
    If Not _condition_ Then
        _VarRef_ = _VariantValue_
        _MemProperty_ = _VarRef_
        _MemProperty_ = _VarRef_
        _CallImp_
        _VarRef_ = _VarRef_
        _CallImp_
        _MemProperty_ = _VarRef_
        _CallImp_
        _VarRef_ = _VarRef_
        _MemProperty_ = _VarRef_
        _MemProperty_ = _VarRef_
        _CallImp_
        _VarRef_ = _MemProperty_
        If Not _condition_ Then
            Exit Sub
            _CallImp_
            _CallImp_
            _CallImp_
            _CallImp_
            1 = "Y"
            _CallImp_
            _CallImp_
            If Not _condition_ Then
                _CallImp_
                If Not _condition_ Then
                    _CallImp_
                    ((("/" = 255) & ("/" & ".")) & ".") = _VarRef_
                    _CallImp_
                    _CallImp_
                    If Not _condition_ Then
                        Exit Sub
                        _CallImp_
                        _CallImp_
                        _CallImp_
                        _CallImp_
                        _CallImp_
                        Exit Sub
End Sub

' --- Proc @ 0x00a9794c (size=1336, frame=340) ---
Private Sub Proc_0x00a9794c()
On Error GoTo ErrHandler
_CallImp_
_CallImp_
_CallImp_
If Not _condition_ Then
    _MemProperty_ = _MemProperty_
    If Not _condition_ Then
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _MemProperty_ = ";"
        1 = "Y"
        _CallImp_
        _VarRef_ = ";"
        1 = "H"
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _VarRef_ = ";"
        _CallImp_
        _MemProperty_ = ";"
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _VarRef_ = ";"
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        _MemProperty_ = ";"
        _CallImp_
        _CallImp_
        100 = ";"
        _CallImp_
        _CallImp_
        _CallImp_
        _Variable_ = ";"
        _CallImp_
        _CallImp_
        If Not _condition_ Then
            Exit Sub
            _CallImp_
            _CallImp_
            Exit Sub
End Sub

' --- Proc @ 0x008f5cd0 (size=40, frame=16) ---
Private Sub Proc_0x008f5cd0()
_CallImp_
_CallImp_
Exit Sub
End Sub

' --- Proc @ 0x009150b0 (size=92, frame=56) ---
Private Sub Proc_0x009150b0()
On Error GoTo ErrHandler
_Property_ = (_MethodCall_ & "\\")
#Date# = "h"
_CallImp_
Exit Sub
End Sub

' --- Proc @ 0x009e3b6c (size=480, frame=312) ---
Private Sub Proc_0x009e3b6c()
On Error GoTo ErrHandler
_Property_ = (_MethodCall_ & "\\")
_CallImp_
_MethodCall_ = _VarRef_
_CallImp_
_CallImp_
If Not _condition_ Then
    Exit Sub
    _CallImp_
    _CallImp_
    1 = "Y"
    _CallImp_
    _VarRef_ = _VariantValue_
    _CallImp_
    If Not _condition_ Then
        _VarRef_ = _VariantValue_
        _CallImp_
        If Not _condition_ Then
            _VarRef_ = _VariantValue_
            _CallImp_
            "." = "."
            "t" = _VarRef_
            _CallImp_
            (_VarRef_ & ".") = _VarRef_
            _CallImp_
            If Not _condition_ Then
                _CallImp_
                _CallImp_
                _CallImp_
                _CallImp_
                Exit Sub
End Sub

