' ==============================================
' Class: ModPeInter
' Procedures: 4
' ==============================================

' --- Proc @ 0x008ea35c (size=28, frame=0) ---
Private Sub Proc_0x008ea35c()
_CallImp_
_CallImp_
_CallImp_
Exit Sub
End Sub

' --- Proc @ 0x0098747c (size=272, frame=240) ---
Private Sub Proc_0x0098747c()
_MemProperty_ = _MemProperty_
If Not _condition_ Then
    If Not _condition_ Then
        If Not _condition_ Then
            "*" = _VariantValue_
            If Not _condition_ Then
                If Not _condition_ Then
                    "*" = _VariantValue_
                    If Not _condition_ Then
                        0 = "*,F( "
                        _CallImp_
                        Exit Sub
End Sub

' --- Proc @ 0x009702cc (size=228, frame=224) ---
Private Sub Proc_0x009702cc()
_var_ = _VariantValue_
_var_ = _VariantValue_
_MemProperty_ = _MemProperty_
If Not _condition_ Then
    If Not _condition_ Then
        "*" = _VariantValue_
        If Not _condition_ Then
            "*" = _VariantValue_
            If Not _condition_ Then
                0 = "*,F( "
                _CallImp_
                Exit Sub
End Sub

' --- Proc @ 0x009afb98 (size=360, frame=256) ---
Private Sub Proc_0x009afb98()
_var_ = _VariantValue_
_var_ = _VariantValue_
_var_ = _VariantValue_
_MemProperty_ = _MemProperty_
If Not _condition_ Then
    If Not _condition_ Then
        "*" = _VariantValue_
        If Not _condition_ Then
            "*" = _VariantValue_
            If Not _condition_ Then
                "*" = _VariantValue_
                If Not _condition_ Then
                    "*" = _VariantValue_
                    If Not _condition_ Then
                        "*" = _VariantValue_
                        If Not _condition_ Then
                            "*" = _VariantValue_
                            If Not _condition_ Then
                                0 = "'D3JA*1J'C3HF "
                                _CallImp_
                                Exit Sub
End Sub

